In [ ]:
#230701513
#VEERANDIRA SARAN R
#II CSE F
#CS23334-Fundamentals of Data Science
#Numpy built in function
import numpy as np
array=np.random.randint(1,100,9)
array

array([17, 47, 58, 40, 70, 98, 97, 33,  1], dtype=int32)

In [3]:
np.sqrt(array)

array([9.38083152, 5.74456265, 8.54400375, 7.21110255, 7.48331477,
       6.244998  , 9.69535971, 8.18535277, 9.21954446])

In [4]:
array.ndim

1

In [5]:
new_array=array.reshape(3,3)
new_array

array([[88, 33, 73],
       [52, 56, 39],
       [94, 67, 85]], dtype=int32)

In [6]:
new_array.ndim


2

In [7]:
new_array.ravel()

array([88, 33, 73, 52, 56, 39, 94, 67, 85], dtype=int32)

In [9]:
newm=new_array.reshape(3,3)
newm

array([[88, 33, 73],
       [52, 56, 39],
       [94, 67, 85]], dtype=int32)

In [10]:
newm[2,1:3]

array([67, 85], dtype=int32)

In [11]:
newm[1:2,1:3]

array([[56, 39]], dtype=int32)

In [12]:
new_array[0:3,0:0]

array([], shape=(3, 0), dtype=int32)

In [13]:
new_array[0:2,0:1]

array([[88],
       [52]], dtype=int32)

In [14]:
new_array[0:3,0:1]

array([[88],
       [52],
       [94]], dtype=int32)

In [15]:
new_array[1:3]

array([[52, 56, 39],
       [94, 67, 85]], dtype=int32)